language: python

python:
  - "2.7"
  - "3.4"

env:
  - DJANGO_VERSION=1.5.10 DRF_VERSION=2.4.4
  - DJANGO_VERSION=1.6.7 DRF_VERSION=2.4.4
  - DJANGO_VERSION=1.7.1 DRF_VERSION=2.4.4
  - DJANGO_VERSION=1.5.10 DRF_VERSION=3.0.2
  - DJANGO_VERSION=1.6.7 DRF_VERSION=3.0.2
  - DJANGO_VERSION=1.7.1 DRF_VERSION=3.0.2

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q djangorestframework==$DRF_VERSION
  - pip install -q djet==0.0.10
  - pip install coveralls
  - python setup.py -q develop

script: coverage run --source=djoser testproject/manage.py test testapp
after_success:
  coveralls