sudo: false
language: python
python:
  - "3.5"
env:
  - TOX_ENV=py26-dj15-drf32
  - TOX_ENV=py26-dj16-drf32
  - TOX_ENV=py27-dj15-drf32
  - TOX_ENV=py27-dj16-drf32
  - TOX_ENV=py27-dj17-drf33
  - TOX_ENV=py27-dj18-drf33
  - TOX_ENV=py27-dj19-drf33
  - TOX_ENV=py32-dj15-drf32
  - TOX_ENV=py32-dj16-drf32
  - TOX_ENV=py33-dj15-drf32
  - TOX_ENV=py33-dj16-drf32
  - TOX_ENV=py34-dj15-drf32
  - TOX_ENV=py34-dj16-drf32
  - TOX_ENV=py32-dj17-drf33
  - TOX_ENV=py33-dj17-drf33
  - TOX_ENV=py34-dj17-drf33
  - TOX_ENV=py32-dj18-drf33
  - TOX_ENV=py33-dj18-drf33
  - TOX_ENV=py34-dj18-drf33
  - TOX_ENV=py35-dj18-drf33
  - TOX_ENV=py34-dj19-drf33
  - TOX_ENV=py35-dj19-drf33

install:
  - travis_retry pip install "virtualenv<14.0.0" "tox>=1.9"

script:
  - tox -e $TOX_ENV

after_success:
  - pip install coveralls==0.5
  - coveralls
