language: python

python:
  - "2.7"
  - "3.4"

env:
  - DJANGO_VERSION=1.5.10
  - DJANGO_VERSION=1.6.7
  - DJANGO_VERSION=1.7

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q djangorestframework==2.4.3
  - python setup.py -q install

script: testproject/manage.py test testapp